config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :posts
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :comments
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    can [:edit, :update, :delete], Post do |post|
      post.user == user
    end

    can [:edit, :update, :delete], Comment do |comment|
      comment.user == comment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, length: { minimum: 6, maximum: 300 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, uniqueness: { case_sensitive: false },
                       presence: true, length: { minimum: 3, maximum: 25 }
  validates :email, uniqueness: { case_sensitive: false },
                    presence: true, length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in to perform this action.'
      redirect_to login_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit update destroy]
  before_action :require_user, only: %i[edit update destroy]

  def new
    if current_user.present?
      @post_id = params[:post_id]
      @comment = Comment.new
    else
      redirect_to login_path
      flash[:notice] = 'Please login to comment'
    end
  end

  def show; end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to post_path(@comment.post)
    else
      flash[:notice] = 'Something Went Wrong.'
      render 'new'
    end
  end

  def edit
    if (can? :edit, @comment)
      flash[:error] = 'You are not allowed to edit others comment'
    end
  end

  def update
    if (can? :update, @comment)
      if @comment.update(comment_params)
        flash[:notice] = 'Comment was updated successfully.'
        redirect_to @post
      else
        render 'edit'
      end
    else
      flash[:error] = 'You are not allowed to update others post'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    if (can? :delete, @comment)
      @comment.destroy
      redirect_to post_path(@post)
    else
      flash[:error] = 'You are not allowed to delete others post'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

  def set_comment
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to posts_path if logged_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]

  def show
  end

  def index
    @posts = Post.paginate(page: params[:page], per_page: 2)
  end

  def edit 
    if !(can? :edit, @post)
      flash[:error] = 'You are not allowed to edit others post'
      redirect_back(fallback_location: root_path)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = 'Post was created successfully.'
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def update
    if (can? :update, @post)
      if @post.update(post_params)
        flash[:notice] = 'Post was updated successfully.'
        redirect_to @post
      else
        render 'edit'
      end
    else
      flash[:error] = 'You are not allowed to update others post'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    if (can? :delete, @post)
      @post.destroy
      redirect_to posts_path
    else
      flash[:error] = 'You are not allowed to delete others post'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :publish_date, :author, :tags)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else
      flash.now[:alert] = 'There was something wrong with your login credentials.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update destroy]

  def show
    @posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account information is successfully updated.'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome to Alpha Post, you have successfully signed up.'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Account and all associated posts successfully deleted'
    redirect_to posts_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = 'You can only edit or delete your own account.'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, option = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = option[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded shadow mx-auto d-block')
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comment.html.erb
<div class="col-8 mb-4">
  <div class="card card-white post">
    <div class="post-heading">
      <div class="float-start image">
        <img src="http://bootdey.com/img/Content/user_1.jpg" class="img-circle avatar"
                    alt="user profile image">
      </div>
      <div class="float-left meta">
        <div class="title h5">
          <%= link_to comment.user.username, user_path(comment.user) %>
          <span  class="text-muted">commented</span>
          <% if logged_in? && current_user == comment.user && @post.comments.last == comment %>
            <div class="float-end">
              <%= link_to comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "m-2" do %>
                <i class="fas fa-trash-alt fa-lg"></i>
              <% end %>
              <%= link_to edit_comment_path(comment), class: "m-2" do %>
                <i class="far fa-edit fa-lg"></i>
              <% end %>
            </div>
          <% end %>
        </div>
        <h6 class="text-muted time"><%= time_ago_in_words(comment.created_at) %> ago</h6>
      </div>
    </div>
    <div class="post-description">
      <p><%= comment.comment %></p>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors' , obj: @comment %>
      <%= form_with(model: @comment, class: "shadow p-3 mb-3 bg-info rounded" , local: true) do |f|%>
        <div class="form-group row mt-2">
          <div class="col">
            <%= f.text_area :comment, rows: 5, class: "form-control shadow rounded" , placeholder: "Enter comment..."
                %>
          </div>
          <%= hidden_field_tag 'post_id' , @post_id %>
        </div>
        <div class="text-center mt-3">
          <%= f.submit "Save" , class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="text-center mt-3 mb-3">
      <%= link_to "[ Cancel and return to posts listing ]" , posts_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<h1 class="text-center mt-4">Edit Comment</h1>
<%= render 'form' %>

app/views/comments/new.html.erb
<h1 class="text-center mt-4">Add New Comment</h1>
<%= render 'form' %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Akash", "#", class: "text-white"%></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA POST", root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Posts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <%= link_to "Create new post", new_post_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "View posts", posts_path, class: "dropdown-item" %>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure ?"} %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Post</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Alpha Post</h1>
      <p class="lead">This is simple AUTHOR POST application</p>
      <hr class="my-4">
      <p>Please sign up to create your own posts</p>
      <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @post %>
      <%= form_with(model: @post, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f|%>
        <div class="form-group row mt-2">
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of post" %>
          </div>
        </div>
        <div class="form-group row mt-2">
          <%= f.label :publish_date, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.date_field :publish_date, class: "form-control shadow rounded", placeholder: "Date of post" %>
          </div>
        </div>
        <div class="form-group row mt-2">
          <%= f.label :author, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :author, class: "form-control shadow rounded", placeholder: "Author of post" %>
          </div>
        </div>
        <div class="form-group row mt-2">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of post" %>
          </div>
        </div>
        <div class="form-group row mt-2">
          <%= f.label :tags, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :tags, rows: 10, class: "form-control shadow rounded", placeholder: "Tags for post" %>
          </div>
        </div>
        <div class="text-center mt-3">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="text-center mt-3 mb-3">
      <%= link_to "[ Cancel and return to posts listing ]", posts_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="container">
  <% @posts.each do |post| %>
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <% if post.user %>
              by <%= link_to post.user.username, user_path(post.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= post.title %>
            </h5>
            <p class="card-text">
              <%= link_to post.description, post_path(post), class: "text-success", target: '_blank' %>
            </p>
            <p class="card-text">
              <%= post&.publish_date&.strftime('%d/%m/%Y %I:%M %p') %>
            </p>
            <%= link_to "View" , post_path(post), class: "btn btn-outline-success" %>
            <% if logged_in? && post.user == current_user %>
              <%= link_to "Edit" , edit_post_path(post), class: "btn btn-outline-info" %>
              <%= link_to "Delete" , post_path(post), method: :delete,
                                        class: "btn btn-outline-danger" , data: {confirm: "Are you sure ?" }%>
            <% end %>
          </div>
          <div class="mt-2 mb-2">
            <%= pluralize(post.comments.count, "comment") %>
          </div>
          <div class="card-footer text-muted">
            Created <%= time_ago_in_words(post.created_at) %> ago,
            Edited <%= time_ago_in_words(post.updated_at) %> ago
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1 class="text-center mt-4">Edit post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1 class="text-center mt-4">Listing all Posts</h1>


<div class="flickr_pagination">
    <%= will_paginate @posts, :container => false %>
</div>

<%= render 'post' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @posts, :container => false %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center mt-4">Create a new post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h2 class="text-center mt-4">
  <%= @post.title %>
</h1>
<div class="row justify-content-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header fst-italic">
        by <%= @post.user.username if @post.user %>
        <%= link_to gravatar_for(@post.user), user_path(@post.user) %>
      </div>
      <div class="card-body">
        <div class="card-text text-start">
          <%= simple_format(@post.description) %>
        </div>
        <% if logged_in? && @post.user==current_user %>
          <%= link_to "Edit" , edit_post_path(@post), class: "btn btn-outline-info" %>
          <%= link_to "Delete" , post_path(@post), method: :delete, class: "btn btn-outline-danger" , data:
                  {confirm: "Are you sure ?" }%>
        <% end %>
        <%= link_to "Add Comment" , new_comment_path(post_id: @post.id),
                      class: "btn btn-outline-secondary" %>
      </div>
      <div class="card-footer text-muted">
        Created <%= time_ago_in_words(@post.created_at) %> ago,
        Edited <%= time_ago_in_words(@post.updated_at) %> ago
      </div>
    </div>
  </div>
  <h3 class="text-center mt-2 mb-4">Comments</h3>
  <div class="container">
    <div class="row justify-content-center">
      <%= render @post.comments %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved.</h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f|%>
        <div class="form-group row mt-2">
          <%= f.label :username, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>
        <div class="form-group row mt-2">
          <%= f.label :email, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>
        <div class="form-group row mt-2">
          <%= f.label :password, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Chosse a password" %>
          </div>
        </div>
        <div class="text-center mt-3">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="text-center mt-3 mb-3">
      <%= link_to "[ Cancel and return to posts listing ]", posts_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Post</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Posts</h1>
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>
<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <%= link_to user.username, user%>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text">
              <%= pluralize(user.posts.count, "post") %>
            </p>
            <%= link_to "View Profile" , user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit Profile" , edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            Joined <%= time_ago_in_words(user.created_at) %> ago
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Post</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4">
  <%= @user.username %>'s Profile
</h1>
<%= gravatar_for @user, size: 200%>
<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile" , edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>
<h3 class="text-center mt-4">Posts</h3>
<div class="flickr_pagination">
  <%= will_paginate @posts, :container => false %>
</div>
<%= render 'posts/post' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @posts, :container => false %>
</div>